# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formulae.sh from the signed release of Glyndor/podup.
# Do not edit by hand — edit the generator and re-run the update workflow.
class Podup < Formula
  desc "Docker-compose translator and runner for rootless Podman"
  homepage "https://github.com/Glyndor/podup"
  version "3.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Glyndor/podup/releases/download/v3.0.0/podup-darwin-arm64"
      sha256 "d42441642933b9f103cf3a1f30ad22672594caca0758f0ceb41e5bbcea5b1410"
    end
    on_intel do
      url "https://github.com/Glyndor/podup/releases/download/v3.0.0/podup-darwin-x86_64"
      sha256 "7e98b4b17d8dbc1ccc8f1b67ee4332efa273674f48c214e1b7f42f7666f5782e"
    end
  end

  def install
    # A bare-binary download stages under its asset name; rename it to the tool.
    bin.install Dir["podup-darwin-*"].first => "podup"
  end

  test do
    system "#{bin}/podup", "--version"
  end
end
