# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formulae.sh from the signed release of Glyndor/podup.
# Do not edit by hand: edit the generator and re-run the update workflow.
class Podup < Formula
  desc "Docker-compose translator and runner for rootless Podman"
  homepage "https://github.com/Glyndor/podup"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.16/podup-darwin-arm64"
      sha256 "e0613f56e35b7f229e2dfac90a9f81fe46b5f0d3dd7baf45feb27864c6d6bd52"
    end
    on_intel do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.16/podup-darwin-x86_64"
      sha256 "00108e291bae2937d3d0074a74106ba5668f1d2d47be84015c65297bf5673013"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.16/podup-linux-arm64"
      sha256 "7397814cb92d5e45e41ef0a8d2990b3aea3ebdeaaf13c933173342eb5048d576"
    end
    on_intel do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.16/podup-linux-x86_64"
      sha256 "ff0faa5043f9dec1cb623a55e2316c5aa7e012d7caafff6ad856a6436667213c"
    end
  end

  def install
    asset = if OS.mac?
      Hardware::CPU.arm? ? "podup-darwin-arm64" : "podup-darwin-x86_64"
    else
      Hardware::CPU.arm? ? "podup-linux-arm64" : "podup-linux-x86_64"
    end
    bin.install asset => "podup"
  end

  test do
    # The argument comes from the generator's table: brew audit --strict
    # requires a test block, and not every product answers --version.
    system "#{bin}/podup", "--version"
  end
end
