# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formulae.sh from the signed release of Glyndor/podup.
# Do not edit by hand: edit the generator and re-run the update workflow.
class Podup < Formula
  desc "Docker-compose translator and runner for rootless Podman"
  homepage "https://github.com/Glyndor/podup"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.8/podup-darwin-arm64"
      sha256 "0cd35218dbac9f9401e440b5b4c863e13be7f7789be574247debbbe2fbf1c7cb"
    end
    on_intel do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.8/podup-darwin-x86_64"
      sha256 "811c54ceafd69dc91848442f39331a4d88863e3908200dcc6ffdf562e570d77e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.8/podup-linux-arm64"
      sha256 "0f2f43880407dab4eab6045039b07c6a548d3a31f53c60c1d17f7ae571ce55b9"
    end
    on_intel do
      url "https://github.com/Glyndor/podup/releases/download/v5.10.8/podup-linux-x86_64"
      sha256 "46fb8c5c830e11c318937c220fca96316cfda9495394cf604867b875333ec547"
    end
  end

  def install
    asset = if OS.mac?
      Hardware::CPU.arm? ? "podup-darwin-arm64" : "podup-darwin-x86_64"
    else
      Hardware::CPU.arm? ? "podup-linux-arm64" : "podup-linux-x86_64"
    end
    bin.install asset => "podup"
  end

  test do
    # The argument comes from the generator's table: brew audit --strict
    # requires a test block, and not every product answers --version.
    system "#{bin}/podup", "--version"
  end
end
