#!/usr/bin/env bash
# Regenerate Formula/*.rb from the latest signed release of each Glyndor product.
#
# Pull-based, mirroring Glyndor/apt: no product pushes into this repository. This
# reads each product's public GitHub release, verifies its signed SHA256SUMS
# against the org release-signing key, and renders a formula that installs the
# macOS binary from that release with the verified checksum. macOS only — Linux
# is served by the apt repo (apt.glyndor.net).
#
# Run by .github/workflows/update.yml on a schedule and on demand.
set -euo pipefail

# The org's Ed25519 release-signing public key (raw, unpadded base64) — the same
# key podup/helmly/unitpm embed; its private half signs SHA256SUMS in every
# release. Verifying against it is what makes the rendered checksum trustworthy
# rather than whatever an attacker-influenced release asset happens to contain.
RELEASE_PUBKEY_B64="HFv7vg5FCY7YyKUDbJhaQSfB9SboJGSblJtFbLmLHzM"

# Products to publish, one per line: repo|formula|Class|description|arm64|x86_64
# `arm64`/`x86_64` are the macOS release asset names. Add a product here once it
# ships macOS binaries with a signed SHA256SUMS. Keep it in step with the apt
# repo's PRODUCTS list where a product ships on both.
PRODUCTS=(
	"Glyndor/podup|podup|Podup|Docker-compose translator and runner for rootless Podman|podup-darwin-arm64|podup-darwin-x86_64"
)

root="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Download a release's SHA256SUMS(+.sig) and verify the signature, failing closed.
verify_sha256sums() { # $1=repo $2=tag
	rm -f "$work/SHA256SUMS" "$work/SHA256SUMS.sig"
	gh release download "$2" --repo "$1" \
		--pattern SHA256SUMS --pattern SHA256SUMS.sig --dir "$work" --clobber
	python3 - "$work/SHA256SUMS" "$work/SHA256SUMS.sig" "$RELEASE_PUBKEY_B64" <<'PY'
import base64, sys
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
msg = open(sys.argv[1], "rb").read()
sig = open(sys.argv[2], "rb").read()
Ed25519PublicKey.from_public_bytes(base64.b64decode(sys.argv[3] + "==")).verify(sig, msg)
print("SHA256SUMS signature verified")
PY
}

# Print the verified SHA-256 of an asset, or fail if it is absent from the manifest.
hash_of() { # $1=asset
	awk -v a="$1" '$2 == a { print $1; found = 1 } END { if (!found) exit 1 }' \
		"$work/SHA256SUMS"
}

mkdir -p "$root/Formula"

for entry in "${PRODUCTS[@]}"; do
	IFS='|' read -r repo formula cls desc arm intel <<<"$entry"

	tag="$(gh release view --repo "$repo" --json tagName --jq .tagName)"
	version="${tag#v}"
	verify_sha256sums "$repo" "$tag"
	arm_sha="$(hash_of "$arm")"
	intel_sha="$(hash_of "$intel")"
	base="https://github.com/$repo/releases/download/$tag"

	cat >"$root/Formula/$formula.rb" <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formulae.sh from the signed release of $repo.
# Do not edit by hand — edit the generator and re-run the update workflow.
class $cls < Formula
  desc "$desc"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/$arm"
      sha256 "$arm_sha"
    end
    on_intel do
      url "$base/$intel"
      sha256 "$intel_sha"
    end
  end

  def install
    # A bare-binary download stages under its asset name; rename it to the tool.
    bin.install Dir["$formula-darwin-*"].first => "$formula"
  end

  test do
    system "#{bin}/$formula", "--version"
  end
end
RB

	echo "rendered Formula/$formula.rb -> $version"
done
